name: source_gen_example_usage

environment:
  sdk: '>=2.12.3 <3.0.0'

dependencies:
  source_gen_example:
    path: ../example
  retrofit: ^3.0.1


dev_dependencies:
  build_runner: ^2.0.0
  build_verify: ^3.0.0
  test: ^1.5.1

dependency_overrides:
  source_gen:
    path: ../source_gen
